version: 2.1
orbs:
  node: circleci/node@5
jobs:
  lint:
    docker:
      - image: node:18
    resource_class: large
    parallelism: 10
    description: Lint the code
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install pnpm packages
          command: pnpm install
      - save_cache:
          name: Save cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
      - run:
          name: Lint the code
          command: pnpm lint:fix
  run-tests:
    docker:
      - image: node:18
    resource_class: large
    parallelism: 10
    description: Run tests
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install pnpm packages
          command: pnpm install
      - save_cache:
          name: Save cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
      - run:
          name: Run tests
          command: pnpm test
      - store_test_results:
          path: ./test-results/
  build:
    docker:
      - image: node:18
    resource_class: large
    parallelism: 10
    description: Build the project
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install pnpm packages
          command: pnpm install
      - save_cache:
          name: Save cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
      - run:
          name: Build the project
          command: pnpm build
  release:
    docker:
      - image: node:18
    resource_class: large
    parallelism: 10
    description: Release the project
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install pnpm packages
          command: pnpm install
      - save_cache:
          name: Save cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
      - run:
          name: Set up git config
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_NAME 
      - run:
          name: Release the project
          command: pnpm release
  publish:
    docker:
      - image: node:18
    resource_class: large
    parallelism: 10
    description: Publish the project
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install pnpm packages
          command: pnpm install
      - save_cache:
          name: Save cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
      - run:
          name: Publish the project
          command: pnpm publish
          environment:
            NPM_TOKEN: $NPM_TOKEN
workflows:
  build-library:
    jobs:
      - lint
      - run-tests:
          requires:
            - lint
      - build:
          requires:
            - run-tests
      - release:
          requires:
            - build
      - publish:
          requires:
            - release
